### ISSUE TITLE
It's slow but cool

### ISSUE THREAD

**Issue by blat-blatnik** [WillardVerschoore/Computer-Graphics-Competition#1]
This is awesome to see from a submission. I've actually been meaning to try ray marching myself for a while now. It's cool to see that you made it work. The DOF effect also looks really cool in the scenes.

I left the Sierpinski Tetrahedron running overnight with an 8K output. Here are the results:

![sierpinski_tetrahedron](https://user-images.githubusercontent.com/55242398/113506103-0d18ab00-9543-11eb-91a0-bd81f527b519.png)

I hope you had fun with the contest and the course!

\- Boris

**Comment by willard-verschoore** [comment]
Wow, that looks great! I must admit that I did not put a lot of time in the Sierpinski Tetrahedron scene as I thought it did not look very good, but at 8k it certainly does! Maybe I will find some time at a later date to look at it again and make it even prettier.

I agree that the ray marcher is slow. There are a lot of optimization that could be made, mainly I would like to have had the time to add multithreading. For very fast (even real time) renders the ray marching should probably be done on the GPU.
